# Generated by Django 6.0.6 on 2026-06-14 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('product_type', models.CharField(choices=[('barrel', 'Бочка'), ('dizhka', 'Діжка')], max_length=10, verbose_name='Тип виробу')),
                ('purpose', models.CharField(choices=[('vodka', 'Горілка'), ('wine', 'Вино'), ('cognac', 'Коньяк'), ('water', 'Вода'), ('cabbage', 'Капуста'), ('tomato', 'Помідори'), ('apple', 'Яблука'), ('cucumber', 'Огірки')], max_length=20, verbose_name='Призначення')),
                ('size_liters', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name="Об'єм (літри)")),
                ('extra_wishes', models.TextField(blank=True, verbose_name='Додаткові побажання')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В роботі'), ('ready', 'Готове'), ('shipped', 'Відправлено'), ('closed', 'Закрито')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Індивідуальне замовлення',
                'verbose_name_plural': 'Індивідуальні замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('barrel', 'Бочка'), ('dizhka', 'Діжка')], max_length=10, verbose_name='Тип виробу')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('purpose', models.CharField(choices=[('vodka', 'Горілка'), ('wine', 'Вино'), ('cognac', 'Коньяк'), ('water', 'Вода'), ('cabbage', 'Капуста'), ('tomato', 'Помідори'), ('apple', 'Яблука'), ('cucumber', 'Огірки')], max_length=20, verbose_name='Призначення')),
                ('size_liters', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name="Об'єм (літри)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Головне фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Ім'я автора")),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка (1-5)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
            },
        ),
    ]
