# Generated by Django 6.0.6 on 2026-06-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='purpose',
            field=models.CharField(choices=[('vodka', 'Горілка'), ('wine', 'Вино'), ('cognac', 'Коньяк'), ('water', 'Вода'), ('cabbage', 'Капуста'), ('tomato', 'Помідори'), ('apple', 'Яблука'), ('cucumber', 'Огірки'), ('other', 'Інше')], max_length=20, verbose_name='Призначення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purpose',
            field=models.CharField(choices=[('vodka', 'Горілка'), ('wine', 'Вино'), ('cognac', 'Коньяк'), ('water', 'Вода'), ('cabbage', 'Капуста'), ('tomato', 'Помідори'), ('apple', 'Яблука'), ('cucumber', 'Огірки'), ('other', 'Інше')], max_length=20, verbose_name='Призначення'),
        ),
    ]
