# Generated by Django 6.0.6 on 2026-06-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customorder_purpose_alter_product_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
